### ISSUE TITLE
Do not mark Links as #broken_attachements

### ISSUE THREAD

**Issue by MHeber** [retorquere/zotero-storage-scanner#11]
Currently, when I run storage scanner, all the attachements that are actually only links to a website (not a snapshot, thus not "real" attachements) are marked as broken. I would really appreaciate if there was a way to change this in storage scanner, letting it check only for real attachments. I hope I could explain the issue, please let me know if it is unclear what I mean. Thank you very much for providing this extension!

**Comment by retorquere** [comment]
Can you shut down Zotero, zip up your zotero.sqlite, and attach it here? Can you also give me the title of one of the links that are erroneously tagged as broken?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.7.34](https://github.com/retorquere/zotero-storage-scanner/releases/download/builds/zotero-storage-scanner-5.0.7.34.xpi) ("addTag strips spaces, hastag does not...").

**Comment by retorquere** [comment]
Can you try .34?

**Comment by MHeber** [comment]
Hi,

I couldnt send you the sqlite file, because it is to large. What to do?

Best, Moritz

**Comment by retorquere** [comment]
Zipping it should do it usually, but first see whether .34 is better.

**Comment by MHeber** [comment]
It did zip it, still too large :))

I also checked out the .34 version which works a lot better — there was only only error…

**Comment by retorquere** [comment]
What error was that?

**Comment by retorquere** [comment]
How large is that zip?

**Comment by MHeber** [comment]
7,7 MB

**Comment by MHeber** [comment]
I updated to the latest test built 7.34 and tried again. It works almost perfectly, there is only one case where a link gets erroneously marked as broken. It is this item (Pressemappe_Deutsches_Museum.pdf):




I am wondering if this issue arises, because I am using zotero on two different machines and the file in question is stored on one PC, while I am running storage scanner on the other — so the link gets marked as broken, because the file lives on another machine?

**Comment by retorquere** [comment]
That would absolutely happen. Tags are synced, but the scanner can only see the local state.

**Comment by MHeber** [comment]
Alright, that explains it. So in other words the issue was fixed with version 34 — thank you again for your help!
Best, Moritz
