### ISSUE TITLE
Get extension signed

### ISSUE THREAD

**Issue by eigengrau** [retorquere/zotero-storage-scanner#2]
I’m very unhappy with Mozilla’s move on extension signing (as with so many of their decisions). However, since Firefox 43.0 is out now (including mandatory signed extensions), and since Zotero Storage Scanner is quite useful, maybe it would make sense to get it signed.

**Comment by retorquere** [comment]
OK, I think it's signed now. Could you please confirm it works for you?

**Comment by eigengrau** [comment]
After updating, the extension could be verified. Thank you kindly!

**Comment by retorquere** [comment]
Super, thanks for the verification.
