### ISSUE TITLE
Can we find files in multiple collections?

### ISSUE THREAD

**Issue by shihabkhan1** [retorquere/zotero-storage-scanner#20]
Would it be possible to identify files in multiple collections via the plugin?

I imported my library from Mendeley. I have many files which feature in more than 1 collection. It is very annoying when we ask zotfile to move and rename those files because it prompts an ask as to which of the collection subdirectories should the file be put in.

If we can identify these files much quicker than the Alt key method, this problem can be resolved.

Any suggestions?

**Comment by retorquere** [comment]
I'm not entirely sure what you mean. Collections don't really "have" items; all items belong to a library, and multiple collections can point to these items, but even if an item appears in several collections, it's still just a single item, not several duplicates.

**Comment by shihabkhan1** [comment]
My apologies. Let me elaborate.
For example: This item is pointed by (contained in) two collections:

1. Engineering/Probabilistic Framework
2. Engineering/Probabilistic Framework/Surrogates and PCE
So when I try to rename the file, zotfile asks me which folder do I want to move the item to on the physical disk as shown in the image below:

[image](https://user-images.githubusercontent.com/24490783/95705519-e6ec0f80-0c71-11eb-9f5a-e11822e611c0.png)

So I was asking, is there a way to figure out such items using the storage scanner plugin which are contained in more than one container? I would simply make sure that they're no longer contained in multiple collections.

Does this explain what I'm talking about?

**Comment by retorquere** [comment]
Storage scanner is targeted to find potential problems with attachments. Since it's generally fine that an item lives in multiple collections, it's not really a problem. It's only a problem in the domain of a specific zotfile behavior. Maybe this kind of detection is better handled in zotfile for that reason.

**Comment by shihabkhan1** [comment]
I see your point. It makes sense.
