### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by raffam** [retorquere/zotero-storage-scanner#3]
I have Zotero v. 4.0.29.17 and the last version of storage scanner, which doesn't seem to work anymore.  When I click on preferences->storage scanner nothing happen

**Comment by retorquere** [comment]
This plugin has no UI. When you select that option, it will silently scan your library and add a tag `#broken` for attachments whose file is missing, and `#duplicates` for references that have more than one attachment of a given type (more than one PDF attachment for example).

**Comment by raffam** [comment]
Thanks you. Is there a documentation for the plugin that I am missing?

**Comment by retorquere** [comment]
You're looking at it 😄

**Comment by BenjaminHCCarr** [comment]
He's being slightly facetious:
There is no UI, it scans in the background but does a far better job than the built in scanner, frankly IU wish @retorquere would @PR this into @Zotero.

For example Zotero marks and PDFs that have supplementary material (many in my field) as duplicates. But `zotero-storage-scanner` does not tag them in `#duplicates`; `#broken` covers a lot of broken things including broken links to files, missing PDFs etc.

So if you run `zotero-storage-scanner` you will see a `zotero` process kick off, and it live updates the  `#duplicates` and`#broken`  smart folders as it goes. If those two folders are empty then you are golden, if there are entries tagged in their then your file/DB has issues to look at.

**Comment by retorquere** [comment]
Thanks for the PR; I didn't mean to be facetious (a word that gets way too little use BTW), it's just that [my comment](https://github.com/retorquere/zotero-storage-scanner/issues/3#issuecomment-306876753) above was at the time the only documentation available :smile: Some of these plugins were created mostly because I had a need at the time, and I didn't figure others would think them useful; I just put them up here for safekeeping.

All of the plugins that people are chiming in on will get the Z5 treatment sooner or later, but BBT takes all my time and then some right now.

**Comment by BenjaminHCCarr** [comment]
oh I know. I know you. You know me. There are docs if you dig around the zot forums (sort of).

But yes, you had a need, and we appreciate you sharing; I doubt you have a metric for how many people are using non `bbt` plugins, maybe you do from XPI pulls.

But bah, I am using 5 non-`bbt` plugins from you.

I know your time is sucked up with `bbt` and it's HUGE user base, so me chiming in here was just trying to be helpful.

**Comment by retorquere** [comment]
And the help is much appreciated :bowing_man:, I was only trying to explain I wasn't intentionally brushing @raffam off.

I honestly have no idea how many users each plugin has. Github downloads stats are fairly useless, and I don't want to foist user tracking on anyone just to stroke my ego.

**Comment by BenjaminHCCarr** [comment]
if you did `tags` or `releases` 😉 

There are many of us....

**Comment by retorquere** [comment]
BBT has releases and tags; download stats are still useless because it shows me "`x` downloaded today" but I have no idea whether those are new installs, upgrades, multiple FF profiles for one user, multiple systems for one user, etc.

All the rest of the plugins will get those as I move the build system I'm putting together for the BBT rewrite.

**Comment by retorquere** [comment]
BTW this plugin will almost certainly not work for Z5. Queued up for rework.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 12](https://github.com/retorquere/zotero-storage-scanner/releases/download/builds/zotero-better-bibtex-5.0.0.12.issue-3.xpi) ("webpack").

**Comment by retorquere** [comment]
Mind that the duplicate detection is still fairly stupid -- it deems attachments duplicates if they're under the same reference and have the same content type. So any two pdfs attached to a single reference will count as a duplicate, and even things that would usually be understood as duplicates (a word and a pdf version of the same text for example) would not be marked as duplicates.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 13](https://github.com/retorquere/zotero-storage-scanner/releases/download/builds/zotero-better-bibtex-5.0.0.13.issue-3.xpi) ("fixes #3").

**Comment by retorquere** [comment]
alright boys & girls -- you know the drill. Try build 13.

**Comment by kld123509945** [comment]
OK, but where could I find the .xpi file? Thanks!

**Comment by retorquere** [comment]
Blip-bloop linked to the xpi

**Comment by retorquere** [comment]
Ah, the link has expired. I'll trigger a new build when I get home tonight, I don't have access to a pc here.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 15](https://github.com/retorquere/zotero-storage-scanner/releases/download/builds/zotero-better-bibtex-5.0.0.15.issue-3.xpi) ("Merge branch 'master' into 3").
