### ISSUE TITLE
zotero 7 support

### ISSUE THREAD

**Issue by heyeruoqi** [retorquere/zotero-storage-scanner#49]
whether this will support zotero7?

**Comment by retorquere** [comment]
At some point, yes, but I'm busy with the Z7 support for BBT.

**Comment by frenchrh** [comment]
Hi Emiliano, I also request an update for zotero-storage-scanner for Zotero 7. 
the current 5.0.12 lists as unsupported on z7.
And its a tool I use all the time, since my large group (75 people) and large collection (20,000 items), means that I regularly need to merge duplicate papers, and then be able to identify when this leads to duplicate attachements. 
Thanks for your support all these years. 
Roger

**Comment by retorquere** [comment]
No updates yet

**Comment by 0xBEAKER** [comment]
I'm going to have to downgrade to Zotero 6 until this plugin is available again - it's that critical to my workflow. I just wanted you to know Emiliano that I appreciate the fact you even made it in the first place.

**Comment by chengwenlong2008** [comment]
> No updates yet

Hi,Emiliano,
我是你来自中国的粉丝，这个插件真的很有用，我们有很多很多人在用，真的很期待他能支持zotero7
感谢！

**Comment by MM-Lehmann** [comment]
What's the main blocker for the incompatibility? Maybe the community can help out?

**Comment by retorquere** [comment]
In the case of this plugin, the conversion from overlay plugin to bootstrapped. It's not a lot of work, but I have made a lot of these plugins over the years.

**Comment by SciImage** [comment]
Please try [Zotero Attachment Scanner](https://github.com/SciImage/zotero-attachment-scanner).
I finally upgraded to Zotero 7 a week ago and really missed the Storage scanner, so I spent some time writing it, with some little improvements.
Of course, this is completely inspired by Zotero Storage scanner, and thank retorquere for his great work!

**Comment by retorquere** [comment]
I'm happy to refer people to your implementation, and retire my plug-in. Have you listed your plug-in on the Zotero wiki?

**Comment by SciImage** [comment]
Hi retorquere, thank you for your support!
Regarding the Zotero Wiki, were you referring to [Plugins for Zotero](https://www.zotero.org/support/plugins)? I didn't realize I could contribute to it, but I'll definitely give it a try.
This is my first plugin for Zotero/Firefox, so I'm still getting familiar with the related resources and API documentation.
