### ISSUE TITLE
Does it really still work?

### ISSUE THREAD

**Issue by ar-jan** [retorquere/zotero-storage-scanner#6]
This looks very useful, as I'm certain I have missing attachments. I saw #3, but I'm pretty sure the plugin's not working for me.

That is, I'm watching System Monitor's processes when I click "Storage Scanner", but no new process appears, and all processes remain practically idle (about 0% cpu usage). Also no #broken or #duplicates folder gets created after waiting a while.

This is with Zotero Standalone 4.0.29.10 (64-bit) and zotero-storage-scanner 0.16, on Ubuntu 14.04.
I've also tried it with Firefox (55.02) and Zotero 4.0.29.10 with the same result.

Is there anything I could do to find out why it's not working?

**Comment by retorquere** [comment]
Not really; when the BBT port to Z5 is done I can have a look. The plugin is pretty simple, so it should be an easy fix.

**Comment by ar-jan** [comment]
Sounds good. And btw, it's great to see you're tackling this complicated port to Z5, much appreciated.

**Comment by raivivek** [comment]
Now that Zotero 5 is available, is there any plan of porting it?

**Comment by kld123509945** [comment]
Dear retorquere, I find that the zotero is so unfriendly with the disabled attachment, including PDFs &notes.   Please help us with the broken attachment links.

**Comment by kld123509945** [comment]
I cannot beg for a scaner to delete duplicate PDFs &notes due to the size and CRC32, but please show us the duplicate items and let us to choose which version of PDF &note should be remained. Then delete the other PDFs &notes in Zotero.

**Comment by retorquere** [comment]
Progress on this is being tracked on #3
